services:
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./backend:/code/backend
            - static_files:/code/backend/staticfiles
            - ./media:/code/backend/media
        ports:
            - "8000:8000"
        networks:
            - main

        command: >
          sh -c "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn mehratech.wsgi:application --bind 0.0.0.0:8000"
        restart: on-failure

    # frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile

    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - ./frontend:/code/frontend
    #     container_name: frontend
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     depends_on:
    #         - backend

        # command: tail -f /dev/null

    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        container_name: nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
            - static_files:/code/backend/staticfiles
            - ./media:/code/backend/media
            # - ./frontend/build:/app/frontend_build  
        ports:
            - "80:80"
        depends_on:
            - backend
            # - frontend
        networks:
            - main
        restart: on-failure
        
networks:
  main:
    driver: bridge

volumes:
  static_files: